# Generated by Django 5.1.3 on 2025-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_remove_transferfindingfinding_engagement_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_acceptance',
            name='long_term',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, this risk acceptance is considered long term.', verbose_name='Long Term'),
        ),
    ]
