# Generated by Django 5.1.15 on 2026-01-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0270_input_inputengagement_inputfile_inputsecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputengagement',
            name='engagement',
            field=models.ForeignKey(
                to='dojo.engagement',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]