# Generated by Django 5.1.15 on 2026-02-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0271_alter_max_length_unique_id_from_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfinding',
            name='note',
            field=models.ManyToManyField(blank=True, editable=False, to='dojo.notes'),
        ),
    ]
