# Generated by Django 5.1.15 on 2026-02-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0271_riskacceptanceengagement_riskacceptanceexclusionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='accepted_by',
            field=models.CharField(blank=True, default=None, help_text='The person that accepts the risk, can be outside of DefectDojo.', max_length=200, null=True, verbose_name='Accepted By'),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='accepted_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is accepted', null=True),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance expires, the findings will be reactivated (unless disabled below).', null=True),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='expiration_date_handled',
            field=models.DateTimeField(blank=True, default=None, help_text='(readonly) When the risk acceptance expiration was handled (manually or by the daily job).', null=True),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='expiration_date_warned',
            field=models.DateTimeField(blank=True, default=None, help_text='(readonly) Date at which notice about the risk acceptance expiration was sent.', null=True),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='notes',
            field=models.ManyToManyField(editable=False, null=True, to='dojo.notes'),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='owner',
            field=models.ForeignKey(help_text='User in DefectDojo owning this acceptance. Only the owner and staff users can edit the risk acceptance.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user'),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='reactivate_expired',
            field=models.BooleanField(default=True, help_text='Reactivate findings when risk acceptance expires?', verbose_name='Reactivate findings on expiration'),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='reviewed_by',
            field=models.CharField(blank=True, default=None, help_text='The person that reviews the risk acceptance for acceptance long term', max_length=200, null=True, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is reviewed', null=True),
        ),
    ]
