# Generated by Django 5.1.15 on 2026-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0272_riskacceptanceengagement_accepted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskacceptanceexclusionrule',
            old_name='engagement',
            new_name='ra_engagement',
        ),
        migrations.AlterField(
            model_name='riskacceptanceengagement',
            name='notes',
            field=models.ManyToManyField(editable=False, to='dojo.notes'),
        ),
    ]
