# Generated by Django 5.1.15 on 2026-02-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0272_transferfinding_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsecret',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inputsecret',
            name='secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
