# Generated by Django 5.1.15 on 2026-03-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0273_alter_inputsecret_key_alter_inputsecret_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAcceptanceEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('accepted_by', models.CharField(blank=True, default=None, help_text='The person that accepts the risk, can be outside of DefectDojo.', max_length=200, null=True, verbose_name='Accepted By')),
                ('reviewed_by', models.CharField(blank=True, default=None, help_text='The person that reviews the risk acceptance for acceptance long term', max_length=200, null=True, verbose_name='Reviewed By')),
                ('reviewed_date', models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is reviewed', null=True)),
                ('accepted_date', models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is accepted', null=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance expires, the findings will be reactivated (unless disabled below).', null=True)),
                ('expiration_date_warned', models.DateTimeField(blank=True, default=None, help_text='(readonly) Date at which notice about the risk acceptance expiration was sent.', null=True)),
                ('expiration_date_handled', models.DateTimeField(blank=True, default=None, help_text='(readonly) When the risk acceptance expiration was handled (manually or by the daily job).', null=True)),
                ('reactivate_expired', models.BooleanField(default=True, help_text='Reactivate findings when risk acceptance expires?', verbose_name='Reactivate findings on expiration')),
                ('risk_status', models.CharField(choices=[('Risks Active', 'Risks Active'), ('Risks Reviewed', 'Risks Reviewed'), ('Risks Pending', 'Risks Pending'), ('Risks Accepted', 'Risks Accepted')], default='Risks Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('notes', models.ManyToManyField(editable=False, to='dojo.notes')),
                ('owner', models.ForeignKey(help_text='User in DefectDojo owning this acceptance. Only the owner and staff users can edit the risk acceptance.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='long_risk_acceptances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.riskacceptanceengagement'),
        ),
        migrations.CreateModel(
            name='RiskAcceptanceExclusionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('exclusions', models.JSONField(blank=True, null=True)),
                ('type_rule', models.CharField(choices=[('CUSTOM', 'CUSTOM'), ('BUSINESS', 'BUSINESS')], default='CUSTOM')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ra_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.riskacceptanceengagement')),
            ],
        ),
    ]
