# Generated by Django 5.1.15 on 2026-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0275_hcparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='transfer_finding/%Y/%m/%d', verbose_name='Proof'),
        ),
        migrations.AlterField(
            model_name='hcparticipation',
            name='business_criticality',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High')], help_text='Business criticality at evaluation time', max_length=20, null=True),
        ),
    ]
