# Generated by Django 5.1.15 on 2026-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0276_riskacceptanceengagement_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={},
        ),
        migrations.AlterField(
            model_name='hcparticipation',
            name='recommendation',
            field=models.CharField(choices=[('postulated', 'Postulated to Continuous Pentesting'), ('manual_postulated', 'Manually Postulated to Continuous Pentesting'), ('already_in_hc', 'Already in Continuous Pentesting'), ('not_eligible', 'Not eligible')], help_text='System recommendation based on business rules', max_length=20),
        ),
    ]
