# Generated by Django 5.1.15 on 2026-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0276_riskacceptanceengagement_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingexclusion',
            name='type',
            field=models.CharField(choices=[('white_list', 'white_list'), ('black_list', 'black_list'), ('zero_day', 'zero_day')], max_length=12),
        ),
    ]
