# Generated by Django 5.1.15 on 2026-05-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0276_riskacceptanceengagement_path_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="choiceanswer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="choicequestion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="textanswer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="textquestion",
            options={},
        ),
    ]
