# Generated by Django 5.1.15 on 2026-06-01 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0277_hcparticipation_recommendation_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for tracking async execution', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_candidates', models.IntegerField(default=0, help_text='Number of products that passed the CLASSID filter')),
                ('processed_count', models.IntegerField(default=0, help_text='Products processed so far (updated periodically)')),
                ('result_summary', models.JSONField(blank=True, help_text='Final counts per recommendation type', null=True)),
                ('log_entries', models.JSONField(default=list, help_text='Execution log entries [{timestamp, level, message}]')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hc_evaluation_runs', to='dojo.dojo_user')),
            ],
            options={
                'verbose_name': 'HC Evaluation Run',
                'verbose_name_plural': 'HC Evaluation Runs',
                'db_table': 'dojo_hc_evaluation_run',
                'ordering': ['-create_date'],
            },
        ),
    ]
