# Generated by Django 5.1.15 on 2026-07-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0278_alter_finding_risk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='unique_id_from_tool',
            field=models.CharField(blank=True, help_text='Vulnerability technical id from the source tool. Allows to track unique vulnerabilities over time across subsequent scans.', max_length=3000, null=True, verbose_name='Unique ID from tool'),
        )
    ]
