# Generated by Django 5.1.15 on 2026-06-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0278_alter_answer_options_alter_choiceanswer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputscenario',
            old_name='verificado',
            new_name='verified',
        ),
        migrations.AlterField(
            model_name='inputscenario',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scenario', to='dojo.inputurl'),
        ),
    ]
