# Generated by Django 5.1.15 on 2026-07-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0279_alter_finding_unique_id_from_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={},
        ),
        migrations.AlterField(
            model_name='hcparticipation',
            name='recommendation',
            field=models.CharField(choices=[('postulated', 'Postulated to HC'), ('postulated_manually', 'Postulated to HC (manual)'), ('already_in_hc', 'Already in Hacking Continuous'), ('not_eligible', 'Not eligible')], help_text='System recommendation based on business rules', max_length=20),
        ),
        migrations.CreateModel(
            name='InputFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowName', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement')),
            ],
        ),
        migrations.CreateModel(
            name='InputURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dojo.inputflow')),
            ],
        ),
        migrations.CreateModel(
            name='InputScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time', models.IntegerField(help_text='Enter the time in minutes', verbose_name='estimated_time')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='untested', max_length=30)),
                ('designed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.dojo_user')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='dojo.inputurl')),
            ],
        ),
    ]
