# Generated by Django 5.1.15 on 2026-09-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0281_crossapproval_request_and_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskacceptanceengagement',
            name='cause',
            field=models.CharField(blank=True, help_text='The cause of the long risk acceptance.', max_length=500, null=True, verbose_name='Cause'),
        ),
        migrations.CreateModel(
            name='RiskAcceptanceEngagementEconomicImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the risk acceptance economic impact.', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the risk acceptance economic impact.', null=True, verbose_name='Description')),
                ('control_effectiveness', models.IntegerField(blank=True, help_text='How effective is the control that mitigates the risk?', null=True, verbose_name='Control Effectiveness')),
                ('economic_impact', models.IntegerField(blank=True, help_text='What is the economic impact of the risk?', null=True, verbose_name='Economic Impact')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('risk_acceptance_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.riskacceptanceengagement')),
            ],
        ),
    ]
