# Generated by Django 5.2.17 on 2026-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0283_crossapproval_owner_and_components'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hcparticipation',
            options={'ordering': ['-create_date'], 'verbose_name': 'Specialized DevSecOps Testing Request', 'verbose_name_plural': 'Specialized DevSecOps Testing Requests'},
        ),
        migrations.AlterField(
            model_name='hcparticipation',
            name='recommendation',
            field=models.CharField(choices=[('postulated', 'Postulated to Specialized DevSecOps Tests'), ('postulated_manually', 'Postulated to Specialized DevSecOps Tests (manual)'), ('already_in_hc', 'Already in Specialized DevSecOps Tests'), ('not_eligible', 'Not eligible')], help_text='System recommendation based on business rules', max_length=20),
        ),
    ]
