# Generated by Django 5.1.15 on 2026-09-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0283_alter_hcparticipation_options_finding_scenarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='scenarios',
        ),
    ]
