# Generated by Django 5.1.15 on 2026-09-25 03:55

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0285_inputflow_findings_alter_sla_configuration_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='long_risk_acceptance_approved',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('webhooks', 'webhooks'), ('alert', 'alert')], default=('mail', 'alert'), help_text='Get notified when a long risk acceptance is requested', max_length=33, verbose_name='Long Risk Acceptance Request'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='long_risk_acceptance_expiration',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('webhooks', 'webhooks'), ('alert', 'alert')], default=('mail', 'alert'), help_text='Get notified when a long risk acceptance is about to expire', max_length=33, verbose_name='Long Risk Acceptance Expiration'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='long_risk_acceptance_rejected',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('webhooks', 'webhooks'), ('alert', 'alert')], default=('mail', 'alert'), help_text='Get notified when a long risk acceptance is rejected', max_length=33, verbose_name='Long Risk Acceptance Rejected'),
        )
    ]
