# Generated by Django 5.1.15 on 2026-09-28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0286_notifications_long_risk_acceptance_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_created",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval request is created", max_length=33, verbose_name="Cross-Approval Created"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_approved",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval request is approved", max_length=33, verbose_name="Cross-Approval Approved"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_rejected",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval request is rejected", max_length=33, verbose_name="Cross-Approval Rejected"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_expired",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval request or exclusion expires", max_length=33, verbose_name="Cross-Approval Expired"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_reopened",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval exclusion is reopened", max_length=33, verbose_name="Cross-Approval Reopened"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_discussion",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a discussion is added to a cross-approval request", max_length=33, verbose_name="Cross-Approval Discussion"),
        ),
        migrations.AddField(
            model_name="notifications",
            name="cross_approval_deleted",
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[("slack", "slack"), ("msteams", "msteams"), ("mail", "mail"), ("webhooks", "webhooks"), ("alert", "alert")], default=("alert", "alert"), help_text="Get notified when a cross-approval request is deleted", max_length=33, verbose_name="Cross-Approval Deleted"),
        ),
    ]
