# Generated by Django 5.1.15 on 2026-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0287_notifications_cross_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskacceptanceengagement',
            name='risk_status',
            field=models.CharField(choices=[('Risks Active', 'Risks Active'), ('Risks Reviewed', 'Risks Reviewed'), ('Risks Pending', 'Risks Pending'), ('Risks Accepted', 'Risks Accepted'), ('Risks Rejected', 'Risks Rejected'), ('Risks Expired', 'Risks Expired')], default='Risks Pending', max_length=50),
        ) 
    ]
