# Generated by Django 5.1.15 on 2026-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0287_notifications_cross_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputflow',
            name='findings',
            field=models.ManyToManyField(blank=True, related_name='Input_flows', to='dojo.finding'),
        ),
    ]
